### ISSUE TITLE
help building for esp32 and micropython 1.15?

### ISSUE THREAD

**Issue by ehagerty** [cbrand/micropython-mdns#1]
Hi, very sorry to trouble you but we're using your awesome work to give us better mdns and want to use it with latest MP.  Can you provide a bit of guidance as to what you did - for example in menuconfig - to build using your mdns bits and not the defaults?  Thanks for your time.

**Comment by cbrand** [comment]
Hey @ehagerty 

I haven't actually worked with the newest MicroPython release soon. I will try to take a look into updating the build configuration for MP 1.15 on the weekend if I find time.

Currently for MP 1.13 which I used the config for the board is injected in the docker container which builds the MP image: https://github.com/cbrand/micropython-mdns/blob/main/Dockerfile#L29

It uses for this the hardware flags from here https://github.com/cbrand/micropython-mdns/blob/main/config/boards/MDNS/mpconfigboard.h#L3 which I extracted from the MicroPython code and didn't use menuconfig for the configuration as far as I remember.

If I manage to find some time on the weekend I can take a look to port the current config to 1.15. I already saw in your fork that you did some work there already though so am not quite sure if I can get it to work.

**Comment by ehagerty** [comment]
Hi @cbrand thank you so much for replying at all sir!  I apologise if my git etiquette is lacking - I'm an old guy learning new tricks!  Thank you so much for such a superb job with this repo in the first place - you not only made it possible for us to move ahead with a pilot for elderly care, but wow are you thorough!  In any case, I've done a lot of (probably crude) refactoring parts of your code to suit what I'm trying to do and probably haven't pushed any of that yet.  So that I don't step on anyone's toes - what /should/ I be doing as I adapt your repo for a somewhat different use case?  By that I mean should I be creating a different repo or trying to fit it back to yours?  Also happy to communicate outside this bug report - just tell me what is appropriate.  Again, thanks so very much for your time.

**Comment by cbrand** [comment]
Hey @ehagerty 

Feel free to issue a pull request if you manage to back port something. I am glady checking it and give feedback / merge it if it is of value for the whole project.

Ideally you should create a PR (Pull Request) describing the changes you've made and what you hope to achieve there. Most bigger projects have a CLA (Contribution License Agreement) but as this is a small project at the moment so as long as you are willing to release the code under the same license (MIT) and make it available for the public.

Just don't be overly surprised if the PR check takes a bit or is rejected. I do my best effort to explain why if that would happen. Otherwise it is always good that you work on your own base repository of course so you don't have to wait for me (or any other contributor of an OSS project) to react.

**Comment by cbrand** [comment]
@ehagerty 

I managed to successfully create an image with MicroPython 1.15 which did include the `micropython-mdns` library.

It successfully managed to do service discovery in my local home Wifi. You can either download the firmware in the newly created [`1.0.0`](https://github.com/cbrand/micropython-mdns/releases/tag/1.0.0) release or use the Makefile or Dockerfile to build it yourself.

This can be done by doing running:
```bash
make compile-micropython-1-15
```

You require docker to be installed on your machine for that.

Hope that helps. Best of luck with your project!

**Comment by ehagerty** [comment]
@cbrand you are the GREATEST!  I am so very grateful for you taking time out of your life to make this possible for us - a very great help indeed.  If I can ever be of assistance to you please just reach out.
